# This is a basic workflow to help you get started with Actions
name: Download Files

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch: {} # Enables manual triggering

permissions:
  contents: write

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download XML file
        run: wget https://opop.pro/tNDLMbEKLUzN -O playlist.xml

      - name: Download M3U file
        run: wget https://opop.pro/JpHvMzWhr5gNbDT -O playlist.m3u

      - name: Display downloaded files
        run: |
          echo "Files downloaded successfully:"
          ls -la playlist.*
          echo "XML file size:"
          wc -l playlist.xml
          echo "M3U file size:"
          wc -l playlist.m3u
